# Generated by Django 2.2.16 on 2020-12-18 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
