# Generated by Django 2.2.16 on 2021-01-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20210112_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.TextField(max_length=500),
        ),
    ]
