# Generated by Django 2.2.16 on 2021-01-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20210112_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='images/'),
        ),
    ]
