# Generated by Django 2.2.16 on 2021-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20210112_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
